// tilik/ui-svelte/src/lib/components/LogPanel.svelte
<script lang="ts">
    export let data: LogEntry[];

    type Level = 'error' | 'info' | 'debug' | 'warn';
    type LogEntry = {
        context: object;
        level: Level;
        line: string;
        message: string;
        time: number;
    };

    const getLogLevelStyles = (level: Level) => {
        switch (level) {
            case 'debug':
                return { color: 'rgb(54, 96, 146)' };
            case 'info':
                return { color: 'rgb(0, 125, 60)' };
            case 'warn':
                return { color: 'rgb(225, 125, 50)' };
            case 'error':
                return { color: 'rgb(240, 0, 0)' };
            default:
                return {};
        }
    };
</script>

<div class="log-panel">
    {#if !data || data.length === 0}
        <div class="alert info">
            <h3>No logs found during the process</h3>
        </div>
    {:else}
        <div class="table-container">
            <table>
                <thead>
                    <tr>
                        <th>Timestamp</th>
                        <th>Level</th>
                        <th>Message</th>
                    </tr>
                </thead>
                <tbody>
                    {#each data as entry, index (index)}
                        <tr style="color: {getLogLevelStyles(entry.level).color};">
                            <td>{new Date(entry.time).toLocaleString()}</td>
                            <td>{entry.level}</td>
                            <td>{entry.message}</td>
                        </tr>
                    {/each}
                </tbody>
            </table>
        </div>
    {/if}
</div>

<style>
    .log-panel {
        margin: 20px;
    }
    .alert {
        padding: 15px;
        border-radius: 5px;
        margin-bottom: 20px;
    }
    .alert.info {
        background-color: #e0f7fa;
        border: 1px solid #00bcd4;
        color: #006064;
    }
    .table-container {
        overflow-x: auto;
    }
    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 10px;
    }
    th, td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }
    th {
        background-color: #f2f2f2;
    }
    tr:nth-child(even) {
        background-color: #f9f9f9;
    }
    tr:hover {
        background-color: #f1f1f1;
    }
</style>

// tilik/ui/src/Module/Debug/Component/Panel/LogPanel.tsx
import {FilePresent} from '@mui/icons-material';
import {
    Alert,
    AlertTitle,
    Link,
    Table,
    TableBody,
    TableCell,
    TableContainer,
    TableHead,
    TableRow,
    Paper,
} from '@mui/material';
import Box from '@mui/material/Box';
import {parseFilePathWithLineAnchor} from '@maintenis/tilik-sdk/Helper/filePathParser';
import {JsonRenderer} from '@yiisoft/yii-dev-panel/Module/Debug/Component/JsonRenderer';
import React from 'react';

type Level = 'error' | 'info' | 'debug' | 'warn';
type LogEntry = {
    context: object;
    level: Level;
    line: string;
    message: string;
    time: number;
};
type LogPanelProps = {
    data: LogEntry[];
};

const getLogLevelStyles = (level: Level) => {
    switch (level) {
        case 'debug':
            return { backgroundColor: 'transparent', color: 'rgb(54, 96, 146)' };
        case 'info':
            return { backgroundColor: 'transparent', color: 'rgb(0, 125, 60)' };
        case 'warn':
            return { backgroundColor: 'transparent', color: 'rgb(225, 125, 50)' };
        case 'error':
            return { backgroundColor: 'transparent', color: 'rgb(240, 0, 0)' };
        default:
            return {};
    }
};

export const LogPanel = ({data}: LogPanelProps) => {
    if (!data || data.length === 0) {
        return (
            <Box m={2}>
                <Alert severity="info">
                    <AlertTitle>No logs found during the process</AlertTitle>
                </Alert>
            </Box>
        );
    }
    return (
        <TableContainer component={Paper}>
            <Table sx={{minWidth: 650}} aria-label="log table">
                <TableHead>
                    <TableRow>
                        <TableCell>Timestamp</TableCell>
                        <TableCell>Level</TableCell>
                        <TableCell>Message</TableCell>
                    </TableRow>
                </TableHead>
                <TableBody>
                    {data.map((entry, index) => (
                        <TableRow
                            key={index}
                            sx={{
                                backgroundColor: getLogLevelStyles(entry.level).backgroundColor,
                                '&:last-child td, &:last-child th': {border: 0}
                            }}
                        >
                            <TableCell component="th" scope="row" sx={{ color: getLogLevelStyles(entry.level).color }}>
                                {new Date(entry.time).toLocaleString()}
                            </TableCell>
                            <TableCell sx={{ color: getLogLevelStyles(entry.level).color }}>{entry.level}</TableCell>
                            <TableCell sx={{ color: getLogLevelStyles(entry.level).color }}>{entry.message}</TableCell>
                        </TableRow>
                    ))}
                </TableBody>
            </Table>
        </TableContainer>
    );
};
